name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Release build
        run: ./gradlew assembleRelease
      - name: Source jar and dokka
        run: ./gradlew :glassfy:androidSourcesJar :glassfy:javadocJar :paywall:androidSourcesJar :paywall:javadocJar
      - name: Publish to MavenCentral
        run: ./gradlew :glassfy:publishReleasePublicationToSonatypeRepository :paywall:publishReleasePublicationToSonatypeRepository
        # auto-close staging repository
        # run: ./gradlew :glassfy:publishReleasePublicationToSonatypeRepository --max-workers 1 :glassfy:closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
